// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
   FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIPFFdmz0KUjE9PMuVxLMgdhgMBGxj3YA',
    appId: '1:740956966266:web:a225277b7dc34b2b255ac3',
    messagingSenderId: '740956966266',
    projectId: 'bleapp-6afb9',
    authDomain: 'bleapp-6afb9.firebaseapp.com',
    databaseURL: 'https://bleapp-6afb9-default-rtdb.firebaseio.com',
    storageBucket: 'bleapp-6afb9.appspot.com',
    measurementId: 'G-2CZ3H28Z4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBejZG4BmAY8LYZRwimjjE94Lg4xbrpr9M',
    appId: '1:740956966266:android:a8781845b1b02e22255ac3',
    messagingSenderId: '740956966266',
    projectId: 'bleapp-6afb9',
    databaseURL: 'https://bleapp-6afb9-default-rtdb.firebaseio.com',
    storageBucket: 'bleapp-6afb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwE4i_4CAUn13oTLAdl6o6ez2Tprqrq0',
    appId: '1:740956966266:ios:08f0e5a1b41b3004255ac3',
    messagingSenderId: '740956966266',
    projectId: 'bleapp-6afb9',
    databaseURL: 'https://bleapp-6afb9-default-rtdb.firebaseio.com',
    storageBucket: 'bleapp-6afb9.appspot.com',
    iosClientId: '740956966266-juv4rtci3jept7j8juhj29p5a4r191ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
